name: Report a Bug
description: Report a bug related to the Docker Image
title: "[Bug] (enter your title here) "
labels: ["triage"]


body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for your bug report!
        Please provide the following details to help us quickly diagnose and resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to reproduce
      description: |
        Please provide clear steps to reproduce the issue.
        e.g.
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      placeholder: What did you do to encounter the bug?
    validations:
      required: true
  
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: input
    id: dockertag
    attributes:
      label: Docker Image Tag
      description: What specific Docker image tag are you currently using? (e.g., `mautic/mautic:latest`, `mautic/mautic:6.2.6`, `mautic/mautic:5-apache`)
      placeholder: mautic/mautic:latest
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Server Architecture
      description: What's the processor architecture of your server? This helps us understand potential platform-specific issues.
      options:
        - AMD64 (Intel or AMD processors)
        - ARM64 (e.g., Raspberry Pi, AWS Graviton, Apple M-series)
    validations:
      required: true

  - type: input
    id: digest
    attributes:
      label: Docker Image Digest (Optional but helpful)
      description: |
        If you know it, please provide the exact image digest (SHA256 checksum).
        You can often find this using `docker images --digests` or from your deployment logs.
      placeholder: sha256:dea6f32436dfaa2d5ebb42b51682f50dc6f26854e2c724c0973af6e48791c4b7
    validations:
      required: false

  - type: textarea
    id: dockerfile
    attributes:
      label: Dockerfile (if applicable)
      description: |
        If you are using a **custom Dockerfile** to build your image, please paste its contents below.
        **Important:** Omit any sensitive information like secrets, passwords, or API keys.
      placeholder: |
        FROM mautic/mautic:latest
        # Your custom layers here...
    validations:
      required: false

  - type: textarea
    id: dockercompose
    attributes:
      label: Docker Compose (if applicable)
      description: |
        If you are using **Docker Compose** for your setup, please paste the relevant `docker-compose.yml` content below.
        **Important:** Omit any sensitive information like secrets, passwords, or API keys.
      placeholder: |
        services:
          mautic:
            image: mautic/mautic:latest
            # Your service configuration here...
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context (Optional)
      description: Add any other context about the problem here. Screenshots, videos, or logs are welcome!
      placeholder: Anything else that might be helpful?
      rows: 4
    validations:
      required: false

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Please confirm the following before submitting your issue.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/mautic/docker-mautic/blob/mautic5/CODE_OF_CONDUCT.md)
          required: true
        - label: This issue is **NOT** a security vulnerability. (Security vulnerabilities should be reported via the [Security](https://github.com/mautic/docker-mautic/security) tab.)
          required: true