name: Feature Request
description: Suggest an idea or enhancement for Mautic's Docker Image
title: "[Feature] (enter your title here)"
labels: ["triage"]

body:
  - type: markdown
    attributes:
      value: |
        ### Share your brilliant idea!
        We appreciate your suggestions for improving the Docker Image. Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem?
      description: |
        Please provide a clear and concise description of the problem you're trying to solve.
        (e.g., "I'm always frustrated when [X] happens...")
      placeholder: What problem does this feature aim to address?
    validations:
      required: false

  - type: textarea
    id: proposed_solution
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen or how you envision the feature working.
        Be specific about how this would improve the Docker Image.
      placeholder: How would you like this feature to function?
    validations:
      required: true

  - type: textarea
    id: alternative_solutions
    attributes:
      label: Describe alternatives you've considered (Optional)
      description: |
        A clear and concise description of any alternative solutions or approaches you've thought about.
        Why did you choose your proposed solution over these alternatives?
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (Optional)
      description: Add any other context, screenshots, or mockups about the feature request here.
      placeholder: Anything else that might be helpful?
    validations:
      required: false

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Please confirm the following before submitting your issue.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/mautic/docker-mautic/blob/mautic5/CODE_OF_CONDUCT.md)
          required: true
        - label: This issue is **NOT** a security vulnerability. (Security vulnerabilities should be reported via the [Security](https://github.com/mautic/docker-mautic/security) tab.)
          required: true