name: Create a Project Task
description: This template shall be used by maintainers to create project tasks
title: "[Task] (enter your title here)"

body:
    - type: textarea
      id: description
      attributes:
        label: Describe the task
        description: A clear description of what the task is.
      validations:
        required: true