name: General Question
description: Ask a general question about the Docker Image
title: "[Question] (enter your question here)"
labels: ["needs triage", "question"]

body:
  - type: markdown
    attributes:
      content: |
        ### Got a question? Ask away!
        We're here to help. Please provide enough detail so we can understand your question clearly.

  - type: textarea
    id: description
    attributes:
      label: Your Question
      description: Please describe your question in detail.
      placeholder: What would you like to know about the Docker Image?
      rows: 8
    validations:
      required: true

  - type: input
    id: topic
    attributes:
      label: Related Topic (Optional)
      description: Is your question related to a specific part of the Docker Image?
      placeholder: e.g., "installation", "updates", "PHP settings"
    validations:
      required: false

  - type: input
    id: dockertag-info
    attributes:
      label: Docker Image Tag (Optional)
      description: If your question relates to a specific Docker Image tag, please provide it.
      placeholder: e.g., mautic/mautic:latest, mautic/mautic:5-apache
    validations:
      required: false

  - type: dropdown
    id: platform-info
    attributes:
      label: Server Architecture (Optional)
      description: If your question might be dependent on server architecture, please indicate.
      options:
        - AMD64 (Intel or AMD processors)
        - ARM64 (e.g., Raspberry Pi, AWS Graviton, Apple M-series)
        - Not applicable
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context (Optional)
      description: Add any extra information that might help us answer your question. Screenshots or logs are welcome!
      placeholder: Anything else that might be relevant?
      rows: 4
    validations:
      required: false

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Please confirm the following before submitting your issue.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/mautic/docker-mautic/blob/mautic5/CODE_OF_CONDUCT.md)
          required: true
        - label: This issue is **NOT** a security vulnerability. (Security vulnerabilities should be reported via the [Security](https://github.com/mautic/docker-mautic/security) tab.)
          required: true