name: PR Tests
permissions:
  contents: read

on:
  pull_request:
    branches:
      - mautic5

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_type: [apache, fpm]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image and export locally (for SAST scan)
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.image_type }}/Dockerfile
          tags: mautic/mautic:${{ matrix.image_type }}-test
          load: true 
          platforms: linux/amd64

      - name: Save image to tar file
        run: docker save mautic/mautic:${{ matrix.image_type }}-test -o ${{ matrix.image_type }}.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image_type }}-image
          path: ${{ matrix.image_type }}.tar

  sast:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.image_type }}-image

      - name: Load Docker image
        run: docker load -i ${{ matrix.image_type }}.tar

      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.30.0
        with:
              image-ref: 'mautic/mautic:${{ matrix.image_type }}-test'
              format: 'table'
              severity: 'CRITICAL,HIGH,MEDIUM'
              exit-code: '1'